# Generated by Django 4.1.7 on 2023-03-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('title', 'published'), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
