# Generated by Django 4.1.7 on 2023-03-21 11:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(default='s'),
            preserve_default=False,
        ),
    ]
