# Generated by Django 4.1.7 on 2023-03-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_text_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='preview',
        ),
    ]
