# Generated by Django 4.1.7 on 2023-03-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_options_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_content',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
