# Generated by Django 4.1.7 on 2023-03-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_categories_alter_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categories',
            new_name='category',
        ),
    ]
