# Generated by Django 4.1.7 on 2023-03-22 10:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_categories_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(auto_created=True, default='s', editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=mptt.fields.TreeForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(upload_to='articles_images/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_content',
            field=models.CharField(max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='articles', to='articles.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childrens', to='articles.category', verbose_name='Родительская категория'),
        ),
    ]
