# Generated by Django 4.1.7 on 2023-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_slug_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(auto_created=True, default='s', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
