# Generated by Django 4.1.7 on 2023-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, max_length=150),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
