# Generated by Django 4.1.7 on 2023-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, max_length=150, null=True),
        ),
    ]
