# Generated by Django 4.1.7 on 2023-03-22 10:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_article_author_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
