# Generated by Django 4.1.7 on 2023-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_slug_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(auto_created=True, editable=False, max_length=100),
        ),
    ]
