# Generated by Django 4.1.7 on 2023-03-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_article_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
