# Generated by Django 4.1.7 on 2023-04-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-published',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
