# Generated by Django 4.1.7 on 2023-03-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_ip_remove_article_views_article_views'),
        ('customusers', '0002_customuser_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorites',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='users', to='articles.article'),
        ),
    ]
