# Generated by Django 4.1.7 on 2023-03-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0004_alter_customuser_author_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
