# Generated by Django 4.1.7 on 2023-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0006_remove_customuser_favorites_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_article',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('author', 'article'), name='unique_author_article'),
        ),
    ]
