# Generated by Django 4.1.7 on 2023-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0007_remove_favorite_unique_user_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(choices=[(None, 'На рассмотрении'), (True, 'Подтверждено'), (False, 'Отклонено')], default=None)),
            ],
            options={
                'verbose_name': 'Заявка на авторство',
                'verbose_name_plural': 'Заявки на авторство',
                'ordering': ['-id'],
            },
        ),
    ]
