# Generated by Django 4.1.7 on 2023-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0009_alter_authorrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='', max_length=3000, verbose_name='Об авторе'),
        ),
    ]
