# Generated by Django 4.1.7 on 2023-04-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0011_alter_customuser_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
