# Generated by Django 4.1.7 on 2023-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0012_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, default='', max_length=3000, verbose_name='Об авторе'),
        ),
    ]
