# Generated by Django 4.1.7 on 2023-04-22 13:25

import customusers.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0013_alter_customuser_about'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', customusers.models.CustomUserManager()),
            ],
        ),
    ]
