# Generated by Django 4.1.7 on 2023-04-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0014_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
